### ISSUE TITLE
Call recording

### ISSUE THREAD

**Issue by xenxynon** [jacopotediosi/GoogleDialerMod#10]
Hey, call rec option come but says recording failed
Device : Redmi Note 7s (Lavender)
ROM : Voltage OS
Android Version : 12
SDK : 31
Here is a screenshot and the logs
Tried all troubleshooting methods
Magisk and App

![Screenshot_20211106-125736_Phone](https://user-images.githubusercontent.com/85495935/140601956-88719ba8-ab5d-4219-8fe8-f8f277fd4a89.png)
[logcat.txt](https://github.com/jacopotediosi/GoogleDialerMod/files/7490040/logcat.txt)

**Comment by jacopotediosi** [comment]
Hi and thanks for your logcat.

The relevant part there seems the following:
`11-06 12:57:33.848 W/MediaProvider(7205): Failed to fetch original file descriptor
11-06 12:57:33.848 W/MediaProvider(7205): java.io.IOException: stat failed: ENOENT (No such file or directory)
11-06 12:57:33.848 W/MediaProvider(7205): 	at com.android.providers.media.MediaProvider.getFileFromFileDescriptor(MediaProvider.java:5794)
11-06 12:57:33.848 W/MediaProvider(7205): 	at com.android.providers.media.MediaProvider.getOriginalMediaFormatFileDescriptor(MediaProvider.java:5711)
11-06 12:57:33.848 W/MediaProvider(7205): 	at com.android.providers.media.MediaProvider.openTypedAssetFileCommon(MediaProvider.java:7134)
11-06 12:57:33.848 W/MediaProvider(7205): 	at com.android.providers.media.MediaProvider.openTypedAssetFile(MediaProvider.java:7115)
11-06 12:57:33.848 W/MediaProvider(7205): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:548)
11-06 12:57:33.848 W/MediaProvider(7205): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:327)
11-06 12:57:33.848 W/MediaProvider(7205): 	at android.os.Binder.execTransactInternal(Binder.java:1184)
11-06 12:57:33.848 W/MediaProvider(7205): 	at android.os.Binder.execTransact(Binder.java:1143)
11-06 12:57:33.848 W/MediaProvider(7205): Caused by: android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
11-06 12:57:33.848 W/MediaProvider(7205): 	at libcore.io.Linux.stat(Native Method)
11-06 12:57:33.848 W/MediaProvider(7205): 	at libcore.io.ForwardingOs.stat(ForwardingOs.java:853)
11-06 12:57:33.848 W/MediaProvider(7205): 	at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:420)
11-06 12:57:33.848 W/MediaProvider(7205): 	at libcore.io.ForwardingOs.stat(ForwardingOs.java:853)
11-06 12:57:33.848 W/MediaProvider(7205): 	at android.app.ActivityThread$AndroidOs.stat(ActivityThread.java:7742)
11-06 12:57:33.848 W/MediaProvider(7205): 	at android.system.Os.stat(Os.java:919)
11-06 12:57:33.848 W/MediaProvider(7205): 	at com.android.providers.media.MediaProvider.getFileFromFileDescriptor(MediaProvider.java:5788)
11-06 12:57:33.848 W/MediaProvider(7205): 	... 7 more`

Unfortunately, this is a known Google Dialer issue. The call recording feature is broken on some devices due to coding errors made by Google. GoogleDialerMod cannot do more than unlock the feature, which in this case is correctly activated.

**Comment by xenxynon** [comment]
Thanks for the reply

**Comment by xenxynon** [comment]
Hi sorry to disturb but I sent a mail regarding a module to install google dialer systemlessly.

**Comment by Golv** [comment]
You need install Google Dialer app as system app into /system/priv-app/ folder. 
Then delete Google Dialer updates in Google Play and reboot phone.
There are no error after that.  Checked it out on LineageOS 18.1.

**Comment by xenxynon** [comment]
> 

Thanks and it's working for already
