### ISSUE TITLE
What does each switch in the "all switches" tab do?

### ISSUE THREAD

**Issue by drandrew1983** [jacopotediosi/GoogleDialerMod#2]
can you please provide some info about what each setting enable or disable?
at least famous options like call screening and hold for me, etc.
there are 2 issues:
- Hold for me doesn't work, showing activating hild for me (require WiFi) and keep showing activating but not working
- some option made screen not turning on when I get calls

**Comment by jacopotediosi** [comment]
Hi,
In the "all switches" tab the application reports the status of all the flags currently contained in the Phenotype DB. These flags may vary based on the device model, the Country you are in, the installed version of the Google Dialer, and other factors.
The "all switches" tab is designed for debugging or for expert users, because you don't know what each flag does and to understand it you have to reverse the behavior of the Google Dialer.

In the "suggested mods" tab, on the other hand, you can find shortcuts that activate well-understood functions on most devices.
At the moment the suggested mods are:
- Enable call recordings, which enables theese boolean flags: "G__enable_call_recording", "CallRecording__enable_call_recording_for_fi", "G__force_within_call_recording_geofence_value", "G__use_call_recording_geofence_overrides", "G__force_within_crosby_geofence_value"
- Silence call recording alerts, which set to "" (empty string) theese string flags: "CallRecording__call_recording_countries_with_built_in_audio_file",  "CallRecording__call_recording_force_enable_built_in_audio_file_countries", "CallRecording__call_recording_force_enable_tts_countries", "CallRecording__call_recording_countries", "CallRecording__crosby_countries"

You can find what each suggested mods does in the following source file: https://github.com/jacopotediosi/GoogleDialerMod/blob/master/app/src/main/java/com/jacopomii/googledialermod/SuggestedModsFragment.java

Sooner I'll add the following new suggested mods:
- Enable "hold for me", which will enable this boolean flag: "G__enable_atlas"
- Enable call screening, which will enable theese boolean flags: "G__speak_easy_enabled", "G__enable_speakeasy_details", "G__speak_easy_bypass_locale_check", "G__speak_easy_enable_listen_in_button"

If you want you can already activate these functions by manually enabling the above flags in the "all switches" tab.

Some functions may not work for you, because the Google Dialer could check other things besides the Phenotype DB flags to decide whether or not to activate the features (eg Hold for me only works if you have the G__enable_atlas flag set to true AND if your Android version is >= 11.

**Comment by drandrew1983** [comment]
Thank you so much for the fast reply. much appreciated
