### ISSUE TITLE
Record button disappears when the call is picked

### ISSUE THREAD

**Issue by AboodiGamer** [jacopotediosi/GoogleDialerMod#27]
After installing the mod, the Record button appears in the call UI.
However, as soon as the other party answers the call the Record button disappears (rather than turning white)!
I uploaded a logcat regarding the issue.

[logcat.txt](https://github.com/jacopotediosi/GoogleDialerMod/files/8786406/logcat.txt)

**Comment by jacopotediosi** [comment]
Could you please try the [latest version 1.05](https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v1.05)?

I'm closing this issue because it's very old, but if you still have the same problem also with that latest version, please leave a comment and I will reopen it immediately.

In that case, please send me the logcat captured during a call, after starting the Google Dialer in debug mode from adb with the `am start -D com.google.android.dialer` command.
