### ISSUE TITLE
Google Dialer's beta program is full (splashscreen alertdialog improvement)

### ISSUE THREAD

**Issue by thx1200** [jacopotediosi/GoogleDialerMod#48]
## Overview
Getting "Google Dialer is not installed, please install the latest beta."  I am **unable to install the latest beta** because Google Dialer's beta program says it's full, so there is no option.  Dialer version was last updated November 17, 2022.

## Steps to Reproduce
Open GoogleDialerMod

## System Information
- Device and model: OnePlus 9

- ROM and Android version: Android 13 / OxygenOS 13

- Is Google Dialer installed as system app: Yes

- Installed Magisk / other SU Manager version: Magisk 25205

- Installed GoogleDialerMod version:
versionCode=106 minSdk=21 targetSdk=33
versionName=1.06
signatures=PackageSignatures{560a7d version:2, signatures:[8c539576], past signatures:[]}

- Installed Google Dialer version:
versionCode=10681108 minSdk=24 targetSdk=33
versionName=94.0.488803600
signatures=PackageSignatures{470a0ce version:3, signatures:[788396df], past signatures:[]}
versionCode=10079218 minSdk=24 targetSdk=33
versionName=88.0.472595733
signatures=PackageSignatures{5532185 version:0, signatures:[], past signatures:[]}

- Your device language (locale):
[ro.product.locale]: [en-US]

- Your location (country of the SIM and country where you are):
[gsm.sim.operator.iso-country]: [us]

**Comment by jacopotediosi** [comment]
Hi! Thanks for your detailed report!

When the Beta Program on Google Play is full, you can download the APK of the latest Google Dialer beta from [APKmirror](https://www.apkmirror.com/apk/google-inc/google-phone/).
Anyway, installing the latest beta is just a suggestion and the latest stable from Google Play should work as well.

I'm keeping this issue open as a reminder for myself, because probably that Alertdialog message can explain this better and so I think I have to rephrase it.

**Comment by thx1200** [comment]
Thank you I will try that right now.

**Comment by jacopotediosi** [comment]
(For the features that GoogleDialerMod currently unlocks, I recommend using the stable version from Google Play, so you can enjoy automatic updates).

Please also remember that Google Dialer needs to be installed as a system app in order to get permission from Android to record calls, so after installing it from the APK or Google Play, you will need to convert it to a system app using any of the thousands of methods described online.

**Comment by thx1200** [comment]
The apkmirror APK did the trick, it works now.  I also googled a bit and found there's a backdoor way to get into the beta program (maybe?) using a hidden URL.  It says I'm enrolling and to please wait.  So fingers crossed there.  :-)

**Comment by jacopotediosi** [comment]
@thx1200 can you please share that hidden url? Thanks!

**Comment by thx1200** [comment]
https://play.google.com/apps/testing/<package> so in this case it's https://play.google.com/apps/testing/com.google.android.dialer
