### ISSUE TITLE
Enable `silence call recording alerts` flags cause recording failed

### ISSUE THREAD

**Issue by XhstormR** [jacopotediosi/GoogleDialerMod#50]
## Overview
[NOTE]: # ( Give a BRIEF summary about your problem )

When the `silence call recording alerts` flags is enabled, clicking the record button shows that the recording failed. If I turn off the flag of `silence call recording alerts`, the call can be successfully recorded.

recording failed settings:
![image](https://user-images.githubusercontent.com/10527522/211163215-4ad57270-2de9-4e21-ab19-37dde758c444.png)

recording success settings:
![image](https://user-images.githubusercontent.com/10527522/211163360-c85062ef-dead-43a3-bc5e-e00b18bff9da.png)

## System Information
- Device and model: motorola edge 20 pro

- ROM and Android version: Android 12

- Is Google Dialer installed as system app: yes

- Installed Magisk / other SU Manager version: Magisk 25.2

[NOTE]: # ( Paste below the output of the `adb shell "dumpsys package com.jacopomii.googledialermod | grep version"` command )
- Installed GoogleDialerMod version:  versionName=1.06

[NOTE]: # ( Paste below the output of the `adb shell "dumpsys package com.google.android.dialer | grep version"` command )
- Installed Google Dialer version:   versionName=96.0.499579918-publicbeta

[NOTE]: # ( Paste below the output of the `adb shell "getprop | grep locale"` command )
- Your device language (locale): 
```
pstar:/ $ getprop | grep locale
[persist.sys.locale]: [zh-Hans-CN]
[ro.product.locale]: [en-US]
```

[NOTE]: # ( Paste below the output of the `adb shell "getprop | grep iso-country"` command )
- Your location (country of the SIM and country where you are):  live in China
```
pstar:/ $ getprop | grep iso-country
[gsm.operator.iso-country]: [cn,]
[gsm.sim.operator.iso-country]: [cn]
```

## Logcat
[NOTE]: # ( 
Launch the Dialer in Debug mode using the `adb shell "am start -D com.google.android.dialer"` command.
Open another terminal and use the `adb logcat > logs.txt` command to start capturing logs.
Perform the necessary steps to replicate the bug, then press CTRL+C to stop capturing logs.
Attach below the resulting logs.txt file.
)

**Comment by jacopotediosi** [comment]
It seems that Google has changed something recently. This bug was not showing up in com.google.android.dialer_94.0.488803600-publicbeta_10681122. I'll look at it as soon as possible.

**Comment by undermark5** [comment]
I'm curious if they are simply updating the files every time or if they check a hash of the file and overwrite if it doesn't match. Regardless, either way doesn't seem to be solvable from just a dummy file alone, that being said, it is possible to do, just would require more effort and probably not within the scope of this tool. It would be possible to do with something like revanced or frida, but that requires digging through obfuscated decompiled code to figure out where to hook in.

**Comment by jacopotediosi** [comment]
> I'm curious if they are simply updating the files every time or if they check a hash of the file and overwrite if it doesn't match. Regardless, either way doesn't seem to be solvable from just a dummy file alone, that being said, it is possible to do, just would require more effort and probably not within the scope of this tool. It would be possible to do with something like revanced or frida, but that requires digging through obfuscated decompiled code to figure out where to hook in.

Actually digging through their code it's not so difficult and patching could be done also with Xposed, but in that case it will be hooked to a specific version of the Dialer, because each time they compile a new apk, function names are randomized.

However, this tool was just about phenotype.db and filesystem things (and it still could be improved, e.g. as of #51, because I know there are many amazing hidden features in other Google Apps as well). So I agree they may have beaten us about the recording announcements and, at this point, silencing them may be out of scope.

**Comment by jacopotediosi** [comment]
Btw they are replacing files every time a recording is started without checking anything. It may even be a bug and not an intentional behaviour.

**Comment by undermark5** [comment]
> Actually digging through their code it's not so difficult and patching could be done also with Xposed, but in that case it will be hooked to a specific version of the Dialer, because each time they compile a new apk, function names are randomized.

IDK, I was digging through the code trying to find where to bypass the checks that trigger the failure and I wasn't making much progress, but then again, I'm not super experienced in decompiling and reverse engineering.

As for the randomized function names, are you familiar with how revanced works? In theory their patches could work for multiple app versions because rather than looking at method names they check for a fingerprint (combination of strings, opcodes, return types, etc.) in order to find where to patch the bytecode. It's pretty cool.

Definitely out of scope for this though.

**Comment by DraconicNEO** [comment]
> It seems that Google has changed something recently. This bug was not showing up in com.google.android.dialer_94.0.488803600-publicbeta_10681122. I'll look at it as soon as possible.
> 
> Update: currently unsolvable. In latest versions, Google Dialer always tries to rewrite the alert audio with the original one.

Would this issue still occur if we replaced the original files in the APK with the patched ones?

**Comment by jacopotediosi** [comment]
For reference: latest Google Dialer version in which we can silence call recording announcement is https://www.apkmirror.com/apk/google-inc/google-phone/google-phone-94-0-490096008-release/.
I'm going to release a new version of GoogleDialerMod that doesn't allow users to enable the "silence call recording" switch if they have installed Google Dialer > 94.x.

**Comment by jacopotediosi** [comment]
If you had enabled the "silence call recording alerts" mod and you can't disable it anymore because the switch is disabled in the new version of GoogleDialerMod, use the trash can icon at the right in the topbar to remove all mods and reset the Dialer to a working state, then reapply your desidered mods.

**Comment by scarlion1** [comment]
> If you had enabled the "silence call recording alerts" mod and you can't disable it anymore because the switch is disabled in the new version of GoogleDialerMod, use the trash can icon at the right in the topbar to remove all mods and reset the Dialer to a working state, then reapply your desidered mods.

Hi bud, call recordings used to work for me but have stopped for a while.  I tried your above suggestion but still get "recording failed" when I push record button during a call.  Also if I push the button again it doesn't attempt to stop recording but the button remains in an on/activated state and continue to receive "recording failed" messsage.  My settings are below.  Any ideas?  Thanks

- Device and model: Google Pixel 5a
- ROM and Android version: Android 11
- Is Google Dialer installed as system app: yes
- Installed Magisk / other SU Manager version: Magisk 25.1
- Installed GoogleDialerMod version: 2.00
- Installed Google Dialer version: versionName=96.0.499579918-publicbeta
- Your device language (locale): en
- Your location (country of the SIM and country where you are): USA

**Comment by D3it7i** [comment]
I've made an xposed module for anyone who wants to mute or customize sounds for versions after Dialer 94.x to check out:
https://github.com/D3it7i/CallRecordingCustomize

**Comment by scarlion1** [comment]
Thanks @D3it7i I'll give it a try.  So, I'll install your release and then try enable GAppsMod `silence call recording alerts`, there is no need to use `*_custom.wav` files additionally right?

**Comment by D3it7i** [comment]
> Thanks @D3it7i I'll give it a try. So, I'll install your release and then try enable GAppsMod `silence call recording alerts`, there is no need to use `*_custom.wav` files additionally right?

If you don't place *_custom.wav or permissions are incorrect.  Recording prompts will be muted.  Just install my xposed module and enable it, and it will run according to the function designed by my module (custom or silent prompt).  Nothing to do with gappsmod.

**Comment by doomwithdon** [comment]
> > Thanks @D3it7i I'll give it a try. So, I'll install your release and then try enable GAppsMod `silence call recording alerts`, there is no need to use `*_custom.wav` files additionally right?
> 
> If you don't place *_custom.wav or permissions are incorrect. Recording prompts will be muted. Just install my xposed module and enable it, and it will run according to the function designed by my module (custom or silent prompt). Nothing to do with gappsmod.
> 
> If you use a higher version of Dialer, you should still turn off the option of `silence call recording alerts`

I installed your module, deleted the wav files and still could hear the recording announcement. Am I missing something?

**Comment by scarlion1** [comment]
> I installed your module, deleted the wav files and still could hear the recording announcement. Am I missing something?

   @doomwithdon it's probably best to open a new issue on that project's tracker.  That being said, if you delete the official `starting_voice-en_US.wav` and `ending_voice-en_US.wav` they will just get re-created.  That could be interfering.
   For me, having silent starting and ending notifications is fine, and the author has stated: "If the `*_custom.wav` is unreadable or does not exist, the recording prompt will be slient."  Therefore, I did not do anything after installing and activating the module, and I can confirm it works!  The call recording alerts are now silent.
   Maybe try deactivating the module and rebooting your device then re-activate the module, don't mess with any of the *.wav files and see if it works.  If not then like I said probably best to open a new issue on that project's tracker, also include your device make & model, android version, and Google Dialer (Phone) version in case it helps troubleshooting.  Hope you can get it because i've been dealing with the alerts for over 3 months now!
   Good job @D3it7i thank you!!

**Comment by ggs-cto** [comment]
use TTSLexx to silence call recording alerts, it work for me :-)
