### ISSUE TITLE
Can please add Turkish language for announce etc. and others in call screening..

### ISSUE THREAD

**Issue by swx-tr** [jacopotediosi/GoogleDialerMod#62]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Solution
[NOTE]: # ( A clear and concise description of what you want to happen )

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Alternatives
[NOTE]: # ( A clear and concise description of any alternative solutions or features you've considered )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by jacopotediosi** [comment]
For each supported language, the Google Dialer needs to download specific Call Screen artificial intelligence training files from Google servers. Since we cannot train that artificial intelligence, unfortunately we cannot create additional languages for the Call Screen feature. Sorry.

Please open an issue to have new Call Screen languages added to GoogleDialerMod when Google Dialer officially supports them. You can see the list of currently supported languages at the following link: https://support.google.com/phoneapp/answer/9118387
